version: '3.1'
services:
  app:
    container_name: tec-syspass
    image: nuxsmin/docker-syspass:3.0.4
    restart: always
    ports:
      - 8001:80
      - 4431:443
    expose:
      - 80
      - 443 
    links:
      - db
    volumes:
      - /docker/filesystem/syspass/syspass-config:/var/www/html/sysPass/app/config
      - /docker/filesystem/syspass/syspass-backup:/var/www/html/sysPass/app/backup

  db:
    container_name: tec-syspass-db
    restart: always
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    ports:
      - "3306"
    volumes:
      - /docker/filesystem/syspass/syspass-db:/var/lib/mysql

