version: '3.1'

services:
    glpi:
        container_name: tec-glpi
        build: .
        ports:
            - "8006:80"
        expose:
            - 80
        links:
            - mysql:db
        env_file:
            - ./glpi.env
        volumes:
            - /docker/filesystem/glpi/glpi_data:/var/www/html/glpi

    mysql:
        container_name: tec-glpi-db
        image: mariadb
        env_file:
            - ./glpi.env
        volumes:
            - /docker/filesystem/glpi/mysql_data:/var/lib/mysql