version: "3.3"

services:
 glpi:
   image: driket54/glpi
   container_name: tec-glpi
   ports:
     - "8006:80"
   expose:
     - "80"
   links:
     - mysql:db
   env_file:
     - ./glpi.env
 
 mysql:
   image: mariadb
   container_name: tec-glpi-db
   env_file:
     - ./glpi.env
   volumes:
     - /docker/filesystem/mysqldata:/var/lib/mysql